### PR TITLE
Handle undefined data

### PR DESCRIPTION
**Pull request by aeruhxi**

### CODE REVIEW

**Comment by rameshsyn** [comment]
@AbsoluteZero273  Bro, It would be great to have handlers to undefined image too. 
Like fallback to default image

**Comment by aeruhxi** [comment]
Okay, so what should be the default image?

**Comment by rameshsyn** [comment]
like this https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg

**Comment by rameshsyn** [comment]
Instead writing script to handle, we can simply name this image as `undefined.png` :P

**Comment by aeruhxi** [comment]
I think to let it implicitly handle `undefined` like that does not become clear in the code. Anyway, I will continue on this tomorrow. Also, we need to distinguish gender if we use the default picture. :stuck_out_tongue_closed_eyes:

**Comment by rameshsyn** [comment]
@AbsoluteZero273  Yes :+1:

**Pull request merged**
