### PR TITLE
update member.js

### PR DESCRIPTION
**Pull request by sujanrijal16**
Added my detail

### CODE REVIEW

**Comment by axispx** [comment]
Please provide your discriminator and proper indentation. 😄

**Comment by rameshsyn** [comment]
@sujanrijal16  To see your discord username discriminator, click your user name in discord and you will see something like `#8898` next to your username. that's your discrimator :+1:

**Comment by amitness** [comment]
@sujanrijal16 Any updates here?

**Comment by amitness** [comment]
Seems @sujanrijal16 didn't make the changes. I've done it for him. Please check and merge it @rameshsyn.

**Comment by aeruhxi** [comment]
Fixed the indentations. Ready to merge. :smile:

**Pull request merged**
