### PR TITLE
Made changes to the members card

### PR DESCRIPTION
**Pull request by dineshkhadka**

### CODE REVIEW

**Review by rameshsyn — APPROVED** [review]
It seems ok, tested locally, good to go 🚢  👍 
May need to squash commits before merging !

**Review by amitness — APPROVED** [review]
Looks good to me.

**Comment by AbsoluteZero273** [comment]
Thanks for the PR! The page looks better now.

**Review by aeruhxi — APPROVED** [review]
Thanks for the PR! The page looks better now.

**Pull request merged**
