### PR TITLE
Serve images through external source (github)

### LINKED ISSUE #24: Images as assets?
I think it would be better if images were sourced externally. Images will only cause bloat. My suggestion would be to get them via sources like Twitter, Github, etc. that the contributors link with their information.

### PR DESCRIPTION
**Pull request by rameshsyn**
Changes overview
* Updated member addition process.
* Deleted member profile images
* Wrote a script to serve image through github profile image. 
* Fixed a broken link on members page
Closes #24 :+1:

### CODE REVIEW

**Comment by aeruhxi** [comment]
Looks good to me.

**Comment by rameshsyn** [comment]
@AbsoluteZero273  Thank you :dancer:

**Review by aeruhxi — APPROVED** [review]
Good to go :+1:

**Comment by rameshsyn** [comment]
@AbsoluteZero273  Quick tip :stuck_out_tongue: . 
Use this emoji :ship:

**Comment by axispx** [comment]
Thanks for the PR.

**Pull request merged**
