### PR TITLE
bootstrap added

### PR DESCRIPTION
**Pull request by jenish1231**
a simple change to the UI. added bootstrap.

### CODE REVIEW

**Comment by aeruhxi** [comment]
Thanks for the PR! But the objective of this website is to be able to stick to vanilla web technologies (no external dependencies) as much as possible to advance our knowledge. So, I am afraid we can not agree to merge this PR. 
cc @rameshsyn @anarchyrucks

**Comment by rameshsyn** [comment]
Thanks @jenish1231  bro,  As @abs-zero  said, our objective is to challenge ourself by leveraging vanilla techs to solve problems. 
To keep thing simple and consistent we will use vanilla techs at least for this project. If you have any project idea, you can share at our discord server. :)

**Comment by rameshsyn** [comment]
Mr @anarchyrucks , thoughts ?

**Comment by axispx** [comment]
I agree with @rameshsyn and @abs-zero

**Pull request closed without merging**
